# Generated by truthboard's release workflow for v0.9.0 — do not edit.
class Truthboard < Formula
  desc "Task tracking where statuses are derived from git, never typed"
  homepage "https://github.com/emmanuel-D/truthboard"
  version "0.9.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/emmanuel-D/truthboard/releases/download/v0.9.0/truthboard_v0.9.0_darwin_arm64.tar.gz"
      sha256 "3e88780bf77615206f0af7dbe25e3694d53521175ec381f716bfdd57511e707f"
    end
    on_intel do
      url "https://github.com/emmanuel-D/truthboard/releases/download/v0.9.0/truthboard_v0.9.0_darwin_amd64.tar.gz"
      sha256 "b94c7244408cdf0135cecb87bcb325a4574c419e543de95a8bae8700270273e3"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/emmanuel-D/truthboard/releases/download/v0.9.0/truthboard_v0.9.0_linux_arm64.tar.gz"
      sha256 "f53cb82530177f7b354d0ff56e8eed1c224a815b88a90e50fba57f81cc32a2d4"
    end
    on_intel do
      url "https://github.com/emmanuel-D/truthboard/releases/download/v0.9.0/truthboard_v0.9.0_linux_amd64.tar.gz"
      sha256 "0f12d604790d03b0d380b2d256f40ee2d4ae9edc21064384078e73940409f5f4"
    end
  end

  def install
    bin.install "truthboard"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/truthboard version")
  end
end
