# Generated by truthboard's release workflow for v0.24.1 — do not edit.
class Truthboard < Formula
  desc "Task tracking where statuses are derived from git, never typed"
  homepage "https://github.com/emmanuel-D/truthboard"
  version "0.24.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/emmanuel-D/truthboard/releases/download/v0.24.1/truthboard_v0.24.1_darwin_arm64.tar.gz"
      sha256 "afef2814bf586d1455a1c0b7daba4744ad28318d02349e94ed413ea41290406f"
    end
    on_intel do
      url "https://github.com/emmanuel-D/truthboard/releases/download/v0.24.1/truthboard_v0.24.1_darwin_amd64.tar.gz"
      sha256 "b7c16a7c7df3f4981e71dcee6aa477e6f58182a4c055622726394dc8b1d3d5a6"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/emmanuel-D/truthboard/releases/download/v0.24.1/truthboard_v0.24.1_linux_arm64.tar.gz"
      sha256 "5a708f163f58a1adacf60469af35170a93719ad1822e0845a4e81ce75f21ef3c"
    end
    on_intel do
      url "https://github.com/emmanuel-D/truthboard/releases/download/v0.24.1/truthboard_v0.24.1_linux_amd64.tar.gz"
      sha256 "5a2c8f50a11f07df204e6ccb184fbb4e1538d7b54216c3a6c4f5f5667e4cba50"
    end
  end

  def install
    bin.install "truthboard"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/truthboard version")
  end
end
