# Generated by truthboard's release workflow for v0.21.0 — do not edit.
class Truthboard < Formula
  desc "Task tracking where statuses are derived from git, never typed"
  homepage "https://github.com/emmanuel-D/truthboard"
  version "0.21.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/emmanuel-D/truthboard/releases/download/v0.21.0/truthboard_v0.21.0_darwin_arm64.tar.gz"
      sha256 "b0f676aecea88eb78b809cc746b3923ad11201380e0867558c6c216182ccdc49"
    end
    on_intel do
      url "https://github.com/emmanuel-D/truthboard/releases/download/v0.21.0/truthboard_v0.21.0_darwin_amd64.tar.gz"
      sha256 "95bf4872397482bf0acab9a0f441b50eef819864885edcdefb0c413d25be8799"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/emmanuel-D/truthboard/releases/download/v0.21.0/truthboard_v0.21.0_linux_arm64.tar.gz"
      sha256 "bb820c1bcde005014e089a17f8d66f69222a06e6ad08835bf6912496269e5ffa"
    end
    on_intel do
      url "https://github.com/emmanuel-D/truthboard/releases/download/v0.21.0/truthboard_v0.21.0_linux_amd64.tar.gz"
      sha256 "0ecfd9be81038bb266484551e33e1cee0da0e320e41febd6d3baf11e1e249bc9"
    end
  end

  def install
    bin.install "truthboard"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/truthboard version")
  end
end
